name: Continuos Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - uses: action/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: run install, build and test
        run: |
          yarn install
