name: Continuos Integration

on:
  pull_request:
    branch: ['master']

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: action/setup-node@v2
        with:
          node-version: 20.x
      - name: run install, build and test
        run: |
          yarn install
          yarn build
